### PR TITLE
Swagger 3 support

### LINKED ISSUE #47: Update to OpenAPI 3
Update the swagger spec to 3.0 https://swagger.io/specification/

Maybe also rename the repo to make reference to OpenAPI? Any name suggestions?

### PR DESCRIPTION
**Pull request by yonaskolb**
This updates from Swagger 2.0 to **OpenAPI/Swagger 3.0** https://swagger.io/specification
Resolves #47

This includes updating the: 
- `Swagger` parser
- `SwagGen` generator
- Swift template

Note that this initial PR doesn't include all the new Swagger 3 features, but just updates everything to get it working.

Proper support for the following is still missing:
- [ ] [Headers](https://swagger.io/specification/#headerObject)
- [ ] [Examples](https://swagger.io/specification/#exampleObject)
- [ ] [Multiple media types](https://swagger.io/specification/#mediaTypeObject)
- [ ] [Links](https://swagger.io/specification/#linkObject)
- [ ] [Callbacks](https://swagger.io/specification/#callbackObject)
- [ ] [Custom encoding](https://swagger.io/specification/#encodingObject)
- [ ] [Discriminators with oneOf and anyOf](https://swagger.io/specification/#discriminatorObject)
- [ ] [External documentation](https://swagger.io/specification/#externalDocumentationObject)
- [ ] [XML](https://swagger.io/specification/#xmlObject)

Note also that this drops compatibility for Swagger 2.0

### CODE REVIEW

**Comment by cooksimo** [comment]
I've just tried to use this and SPM is reporting unresolvable dependencies for me.

**Comment by yonaskolb** [comment]
@cooksimo are you using this package as a dependency or trying to build this on its own?

**Comment by cooksimo** [comment]
Was attempting to use it as a dependency.

Package.swift contents:
```
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/yonaskolb/SwagGen.git", .branch("swagger_3")),
    ],
```

`swift package generate-xcodeproj` output:
```
Updating https://github.com/onevcat/Rainbow.git
Updating https://github.com/yonaskolb/SwagGen.git
Updating https://github.com/yonaskolb/JSONUtilities.git
Updating https://github.com/kylef/Spectre.git
Updating https://github.com/yonaskolb/Stencil.git
Updating https://github.com/jpsim/Yams.git
Updating https://github.com/kylef/Commander.git
Updating https://github.com/kylef/PathKit.git
Updating https://github.com/SwiftGen/StencilSwiftKit.git
Updating https://github.com/jakeheis/SwiftCLI
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/yonaskolb/SwagGen.git @ swagger_3
warning: PackageDescription API v3 is deprecated and will be removed in the future; used by package(s): JSONUtilities, Stencil
```

**Comment by azimin** [comment]
Checked with my small spec migration, works fine. Will report if we would face anything.
Thanks @yonaskolb

**Comment by yonaskolb** [comment]
Merging this into master. Followup PR's will add more features

**Pull request merged**
