### PR TITLE
Expand IntegerFormat to include more integer types

### PR DESCRIPTION
**Pull request by wqz-leo**
added Int8, Int16, UInt8, UInt16, UInt32, UInt64 in IntegerFormat

### CODE REVIEW

**Review by yonaskolb — COMMENTED** [review]
Cool thanks. Could you add a changelog entry as well

**Comment by wqz-leo** [comment]
Yep fixed.

**Review by yonaskolb — APPROVED** [review]
Great, thanks!

**Comment by yonaskolb** [comment]
I'm not sure why CI is failing...? Have tried to re-run to no avail
```
⚙️  Generating Petstore...
[8](https://github.com/yonaskolb/SwagGen/runs/5765537507?check_suite_focus=true#step:6:8)
error: encountered an I/O error while reading /Users/runner/work/SwagGen/SwagGen/Specs/Petstore/generated/Swift
```

**Comment by yonaskolb** [comment]
Don't think it's related to this PR, so merging. Thanks Leo! 😄

**Comment by wqz-leo** [comment]
Yeah I noticed the CI issue. I tried this locally and all working fine, so not sure what's going on with the CI.

**Pull request merged**
