### PR TITLE
#25 Generate Path Parameters which are defined outside method dictionary

### PR DESCRIPTION
**Pull request by dangthaison91**
I've thought of creating OperationPath (not sure for the name) like this:
```ruby
public struct OperationPath {

    public let absolutePath: String
    public let parameters: [Parameter]

    init(path: String, parameters: [Parameter]) {
        self.absolutePath = path
        self.parameters = parameters
    }
}
```
Then in  `SwaggerSpec`:
```Ruby
      #SwaggerSpec
        var operations: [Operation] = []
        let pathParameters: [Parameter] = jsonDictionary.json(atKeyPath: "parameters") ?? []
        let operationPath = OperationPath(path: path, parameters: pathParameters)

        for method in jsonDictionary.keys {
            if let operationMethod = Operation.Method(rawValue: method), let dictionary = jsonDictionary[method] as? JSONDictionary {

                let operation = try Operation(path: operationPath, method: operationMethod, jsonDictionary: dictionary)
                operations.append(operation)
            }
        }
        self.operations = operations
```
But naming thing is hard and I temporary go with simple implement by adding `pathParameters` to Operation's initializer.

What do you think @yonaskolb ?

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks for this @dangthaison91. Sorry, I missed what you were referring to in the issue you raised.

There is already a class for this called `Endpoint`. Technically in Swagger this is called Path, and should probably be named the same. To avoid clashing with PathKit though I think OperationPath is a fine name. Therefore you can implement your original idea, and refactor Endpoint to OperationPath.

The only thing really missing is the fact that the common parameters are supposed to be overridable, and a parameter is unique based on its name and location. Therefore in the Operation initializer, append only the OperationPath.parameters that aren't already in the Operation.

**Comment by yonaskolb** [comment]
Not exactly what I meant. Instead of adding a new `OperationPath` class, simply rename the existing `Endpoint`

**Comment by dangthaison91** [comment]
@yonaskolb How about  adding `pathParameters` as param of Operation initializer:

```ruby
public class Operation {
    //...
    public init(path: OperationPath, pathParameters: [Parameter], method: Method, jsonDictionary: JSONDictionary) throws {
        parameters = jsonDictionary.json(atKeyPath: "parameters") ?? []
        parameters.append(contentsOf: pathParameters)
}
```

I'd like to keep `Endpoint` name:

``` ruby
public class Endpoint {

    public let path: String
    public let pathParameters: [Parameter]
    public let operations: [Operation]

    required public init(path: String, jsonDictionary: JSONDictionary) throws {
        self.path = path
        pathParameters = jsonDictionary.json(atKeyPath: "parameters") ?? []
        // ......................

        for method in jsonDictionary.keys {
            if let operationMethod = Operation.Method(rawValue: method), let dictionary = jsonDictionary[method] as? JSONDictionary {
                let operation = try Operation(path: operationPath, pathParameters: pathParameters, method: operationMethod, jsonDictionary: dictionary)
                operations.append(operation)
            }
        }
        self.operations = operations
}
```

**Comment by yonaskolb** [comment]
Yeah, what you've outlined there is fine. If you pass the path string, and the parameters that should do. Leave out the new struct.
To be honest I'm actually looking at maybe replacing the Swagger framework with https://github.com/AttilaTheFun/SwaggerParser, which if happens makes this all moot at some point

**Comment by dangthaison91** [comment]
@yonaskolb I just squashed commits. Please check again.
`SwaggerParser` seems promising.

**Pull request merged**
