### PR TITLE
Adds option for usage of fixed width integer

### LINKED ISSUE #53: SwiftFormatter doesn't make use of IntegerItem.format to support Int32 and Int64
Swagger provides the field *format* for integer types to distinguish between *int32* and *int64* (https://swagger.io/specification/#dataTypeFormat). This field is parsed in **IntegerItem**, though the **SwiftFormatter** ignores it and uses always *Int* as Swift type.
This can lead to loss of data, e.g. when Swagger specification contains int32 and generated code is running on device with 64-bit architecture. Putting a value bigger than int32 max into the field will result in a wrong value on receivers side.

### PR DESCRIPTION
**Pull request by martinknabbe**
This fixes #53 with adding an optional option to the Swift template file.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Awesome, nice one @martinknabbe. I'd like to change this around a bit though. It would be good for the property to be defined in `options` (for a general place and so it can also be changed from the command line) and for non-swift formatters to be unaware of this property.

- Inject `templateConfig` into the CodeFormatter (and the swift subclass)
- parse out the `useFixedWidthIntegerTypes` property from `templateConfig.options` in the SwiftFormatter initializer and set a property within that class

**Comment by martinknabbe** [comment]
Just for clarification. To me the options section in the template file looks like options just for stencil files. Is it intended to put all kind of options in there?

With "Inject `templateConfig`" you mean through initializer, correct? Like:
`public init(spec: SwaggerSpec, templateConfig: TemplateConfig) {`

**Comment by yonaskolb** [comment]
Yep, that's pretty much what I meant. Thanks @martinknabbe!

**Comment by yonaskolb** [comment]
I've renamed the property to `fixedWidthIntegers` and added it to the default template in master 👍

**Comment by prefect42** [comment]
When is this going to be released?
Is there an upcoming release planned?

**Comment by yonaskolb** [comment]
A release will be happening soon. This must be released first https://github.com/xcodeswift/xcproj/pull/191

**Pull request merged**
