### PR TITLE
Avoid '??' has non-optional type warning

### PR DESCRIPTION
**Pull request by marcuswu0814**
螢幕快照 2019-12-03 下午7 16 39

### CODE REVIEW

**Comment by yonaskolb** [comment]
True, something must of gotten change in a refactor. Feel free to update with a PR!

**Comment by marcuswu0814** [comment]
Just forgot to run test, I will fix it ASAP. 😃

**Comment by yonaskolb** [comment]
Whoops sorry, I thought this was an issue as I viewed it through the new github notification interface. This is already a PR! :)

**Comment by marcuswu0814** [comment]
螢幕快照 2019-12-03 下午8 16 21

I have no idea why the compiler say it must be unwrapped when try to build test specs. 😅

**Comment by yonaskolb** [comment]
I think it's because of the double optional, though not sure of the specifics.
Try a 2 step process
```swift
...
let jsonValue = try? JSONSerialization.jsonObject(with: jsonData),
let jsonDictionary = jsonValue as? [String: Any] else {
...
```

**Comment by marcuswu0814** [comment]
I try to change the guard condition to:

```swift
 let jsonDictionary = (try? JSONSerialization.jsonObject(with: jsonData)) as? [String: Any] 
```

the error gone, any suggestion to update the template?

**Comment by yonaskolb** [comment]
Yep, the parenthesis will work too

**Comment by marcuswu0814** [comment]
Which one did you prefer? I can fix that.

**Comment by yonaskolb** [comment]
I don't mind, I'll let you choose :)

**Pull request merged**
