### PR TITLE
Added anyType template option

### PR DESCRIPTION
**Pull request by tapoton**
Added anyType template option to be able to replace, for example `Any` or `[String: Any]` with `AnyCodable` and `[String: AnyCodable]`.

Did not find a way to do it using only template.

### CODE REVIEW

**Comment by mackoj** [comment]
I think it’s a great addition ! I did often do it in my template too.

Please consider updating the Changelog and Readme files.

I will even propose it to enable by default.

Thanks for tour contribution @tapoton.

**Comment by yonaskolb** [comment]
Hi @tapoton, thanks for the PR! As @mackoj noted could you please also add:
- a changelog entry
- an entry to the template (with a value as Any) https://github.com/yonaskolb/SwagGen/blob/master/Templates/Swift/template.yml
- some documentation in the readme in the Swift Template section https://github.com/yonaskolb/SwagGen/blob/master/README.md#swift-template-1

**Comment by tapoton** [comment]
Hi!
Added necessary changes, enabled `Any` -> `AnyCodable` override in default template

**Comment by tapoton** [comment]
Looks like all changes made by `FixturesTests` are valid. Please, take a look

**Comment by mackoj** [comment]
please @tapoton could you consider moving it default value to `Any` as @yonaskolb requested and I think you will be in a good place ;)

**Comment by tapoton** [comment]
My bad, didn't get that at first

**Comment by mackoj** [comment]
@tapoton should your feature use the same option as `codableResponses` ? Because the goal of `codableResponses` is to made the model **Codable**.

**Comment by yonaskolb** [comment]
I think this can stay separate to `codableResponses`

**Pull request merged**
