### PR TITLE
fixed compilation errors in generated code

### PR DESCRIPTION
**Pull request by rocketnik**

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks for this @rocketnik . Yeah, this would fix a compile error in Swift 4 which I'm guessing you're using. A proper Swift 4 update will be coming, but this is a good start and is still Swift 3 compatible.
Can you please run `swift test` and then commit the modified generated fixtures

**Comment by rocketnik** [comment]
Hello @yonaskolb, I made a fix to the code generator (qualifying a name), where I did get a compile error in the generated code before. The tests are failing. I can not really follow them. Could you please have a look at them?

**Comment by yonaskolb** [comment]
There are a bunch of test specs that get generated during testing. If they are different to what is stored the test fails. To fix this just run `swift test` or run tests in Xcode on SwiftGenKit which will generate the files which you can then commit. It's a bit of a funny process :)

**Comment by rocketnik** [comment]
Hell @yonaskolb, the tests are fixed now. Please consider merging the PR.

**Pull request merged**
