### PR TITLE
Add customization support for modelProtocol

### PR DESCRIPTION
**Pull request by mackoj**
In case of an already existing `modelProtocol` file that already conform this adding this conformance by default don't make sense.
Maybe we should consider adding a new variable for enabling or disable this code

### CODE REVIEW

**Comment by yonaskolb** [comment]
To disable this just remove the `modelProtocol` from the options

**Comment by mackoj** [comment]
I will try to better explain myself.

The actual implementation force the modelProtocol to be in Coding.swift what if the user have a modelProtocol file that does way more that what is actually proposed in Coding.swift ?

Maybe we should add a new parameter(modelProtocolDisableDefaultImplememtation) set to false by default and when you need to add custom modelProtocol implementation you could be enabling this feature and it will disable the Coding.swift implementation.

What do you think about that ?

**Comment by yonaskolb** [comment]
If you have a protocol with extra properties or functions, you can make that extend the one the api generates. Does that solve your problem?

If we generate a protocol that isn't implemented in generated code, then it won't compile if it's in a standalone module

**Comment by mackoj** [comment]
I will try to extend it to see If it works.

**Comment by mackoj** [comment]
I can't because of this `Extensions must not contain stored properties` :/

**Comment by mackoj** [comment]
How can I properly add test for this case ? Should I add a new folder of fixtures with a custom template.yml ?

**Comment by yonaskolb** [comment]
Hi @mackoj. Thanks for the PR, but for now I think I'll let you leave this in your custom template.

**Pull request closed without merging**
