### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iamtomcat**
Switched Swagger 2.0 version spec. to OpenAPI 3.0 spec.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @iamtomcat. Could you run tests with `swift test` and then commit the changes. CI checks if there are diffs in some fixtures

**Comment by iamtomcat** [comment]
Totally. Will do now.

**Comment by Kastet** [comment]
Thanks @iamtomcat , can you also remove the mention of `RequestAuthorizer` type as doesn't exist anymore.

**Comment by iamtomcat** [comment]
@Kastet Yeah totally.

**Pull request merged**
