### PR TITLE
Possible reference to MediaItem schema added.

### PR DESCRIPTION
**Pull request by alexruperez**
In order to try to generate mocks https://github.com/yonaskolb/SwagGen/issues/88 of each server response, I have redefined MediaItem schema as a possible reference.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @alexruperez! Could you add a changelog entry as well

**Comment by alexruperez** [comment]
Thanks @yonaskolb, I always forget something! 😅 Done! 🙌

**Comment by yonaskolb** [comment]
@alexruperez this seems to have broken the fixtures. When this PR ran on CI, it didn't fail when it failed to compile the fixtures. I've fixed that so now the errors are properly reported, in the `ci` branch (also moved to github actions)
Test results can be seen here https://github.com/yonaskolb/SwagGen/runs/582688905?check_suite_focus=true

**Comment by alexruperez** [comment]
Exactly the same error that is happening in https://github.com/yonaskolb/SwagGen/pull/240, it's the Rocket fixture, but I don't know how to fix it. 😞

**Comment by yonaskolb** [comment]
Rocket is the only one not compiling, but the others are broken too I believe. If you look at the diff of this PR there are lots of useless inline models being generated

**Comment by yonaskolb** [comment]
@alexruperez this PR seems to have broken things. I'll need to revert it

**Pull request merged**
