### PR TITLE
Restore generation of inline types for all of (#267)

### PR DESCRIPTION
**Pull request by nicholascross**
@ymhuang0808 Can you please take a look and see if this properly addresses the issue you faced with the generation of inline types for all of (#267)

### CODE REVIEW

**Comment by ymhuang0808** [comment]
It works. Thanks for your PR!

**Comment by yonaskolb** [comment]
Great thanks @nicholascross! Could you also add a changelog entry please

**Review by yonaskolb — APPROVED** [review]

**Comment by nicholascross** [comment]
@yonaskolb I added the change log entry was there anything else that needs doing before this can be merged?

**Comment by yonaskolb** [comment]
Sorry, was waiting for the tests to finish and forgot about it 😄

**Pull request merged**
